"""
Produce diagnostic plots for an ensemble generated by 2_run_ensemble.py.

Reads every ``member_*`` directory under ``{base_dir}/ensemble`` and writes a set
of figures summarising what actually varied across the ensemble:

  indicator_maps.png        baseline + per-member indicator field (map view)
  indicator_change.png      cells whose geologic unit differs from the baseline
  param_map_perm.png        log10 permeability field per member
  param_map_porosity.png    porosity field per member
  param_spread.png          per-geom-unit Ksat / porosity draws across members
  pressure_timeseries.png   domain-mean pressure head vs time, one line per member

Member directories are discovered on disk rather than read from metadata.csv,
whose ``member_dir`` column records absolute paths from the machine that ran the
ensemble and goes stale as soon as the run tree is moved.

Pass the same --runname, --grid, --end, and --base-dir used by the earlier steps.

    python 3_visualize_ensemble.py \
      --runname mjb --end 2004-10-03 --base-dir ./data/mjb --time-stride 6
"""

import argparse
import glob
import json
import os
import re

import matplotlib

matplotlib.use("Agg")

import matplotlib.pyplot as plt
import numpy as np
from matplotlib.colors import BoundaryNorm, LinearSegmentedColormap, ListedColormap
from parflow.tools.io import read_pfb


# --- Palette -----------------------------------------------------------------
# Single-hue blue ramp used for every magnitude (sequential) field, so the maps
# read as one system.  Categorical slots are used only where identity matters.
SEQ_BLUE = LinearSegmentedColormap.from_list(
    "seq_blue",
    ["#cde2fb", "#9ec5f4", "#6da7ec", "#3987e5", "#256abf", "#184f95", "#0d366b"],
)
INK = "#0b0b0b"
INK_MUTED = "#52514e"
ACCENT = "#2a78d6"
ACCENT_WARM = "#eb6834"
GRID = "#dcdbd6"

plt.rcParams.update(
    {
        "figure.facecolor": "white",
        "axes.facecolor": "white",
        "axes.edgecolor": GRID,
        "axes.labelcolor": INK_MUTED,
        "axes.titlecolor": INK,
        "text.color": INK,
        "xtick.color": INK_MUTED,
        "ytick.color": INK_MUTED,
        "grid.color": GRID,
        "font.size": 9,
        "axes.titlesize": 10,
        "legend.frameon": False,
    }
)


def parse_args():
    parser = argparse.ArgumentParser(
        description="Plot diagnostics for a perturbed ParFlow ensemble.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )

    # --- Path resolution (must match 0_subset_baseline.py) ---
    parser.add_argument("--runname", default="conus2_run")
    parser.add_argument("--grid", default="conus2")
    parser.add_argument("--end", default="2005-10-03", help="Run end date; used to derive water year")
    parser.add_argument("--base-dir", default="./run")
    parser.add_argument(
        "--out-dir",
        default=None,
        help="Directory for the figures (default: {base_dir}/ensemble/figures)",
    )

    # --- Plot controls ---
    parser.add_argument(
        "--layer",
        type=int,
        default=-1,
        help="z index of the layer shown in map views; -1 is the top (land surface) layer",
    )
    parser.add_argument(
        "--max-members",
        type=int,
        default=None,
        help="Plot only the first N members (default: all)",
    )
    parser.add_argument(
        "--time-stride",
        type=int,
        default=1,
        help="Read every Nth pressure file for the timeseries; raise this for long runs",
    )
    parser.add_argument(
        "--skip-timeseries",
        action="store_true",
        help="Skip the pressure timeseries (the only expensive part of this script)",
    )
    parser.add_argument("--dpi", type=int, default=150)

    return parser.parse_args()


def resolve_paths(args):
    water_year = args.end[:4]
    run_tag = f"{args.runname}_{args.grid}_{water_year}WY"
    base_dir = os.path.abspath(args.base_dir)
    return {
        "static_dir": os.path.join(base_dir, "inputs", run_tag, "static"),
        "baseline_runscript": os.path.join(base_dir, "outputs", run_tag, f"{args.runname}.yaml"),
        "ensemble_dir": os.path.join(base_dir, "ensemble"),
    }


def find_members(ensemble_dir, max_members=None):
    """Return [(member_id, member_dir), ...] discovered on disk, in member order."""
    dirs = sorted(glob.glob(os.path.join(ensemble_dir, "member_*")))
    members = [(os.path.basename(d).split("_", 1)[1], d) for d in dirs if os.path.isdir(d)]
    if not members:
        raise FileNotFoundError(
            f"No member_* directories found in {ensemble_dir}.\nRun 2_run_ensemble.py first."
        )
    if max_members is not None:
        members = members[:max_members]
    return members


def load_perturbations(members):
    """Return {member_id: geom_params dict}, skipping members without a record."""
    out = {}
    for member_id, member_dir in members:
        path = os.path.join(member_dir, "perturbation.json")
        if not os.path.isfile(path):
            print(f"  [warn] no perturbation.json for member {member_id}")
            continue
        with open(path) as f:
            out[member_id] = json.load(f).get("geom_params", {})
    return out


def load_field(member_dir, filename):
    path = os.path.join(member_dir, filename)
    if not os.path.isfile(path):
        return None
    return read_pfb(path)


def active_mask(member_dir, runname, shape):
    """
    Boolean mask of active cells.

    ParFlow writes a large negative sentinel (-3.4e38) into inactive cells, so
    averaging without a mask returns nonsense.  ``{runname}.out.mask.pfb`` is the
    3D mask; the subsetted ``mask.pfb`` input is 2D and gets broadcast over z.
    """
    mask = load_field(member_dir, f"{runname}.out.mask.pfb")
    if mask is None:
        mask = load_field(member_dir, "mask.pfb")
    if mask is None:
        return np.ones(shape, dtype=bool)
    active = mask > 0
    if active.shape != shape:
        active = np.broadcast_to(active.reshape(-1, *shape[1:])[0], shape)
    return active


def grid_layout(n):
    ncols = min(4, n)
    nrows = int(np.ceil(n / ncols))
    return nrows, ncols


def new_map_grid(n, title, dpi, aspect=1.0, title_lines=1):
    """Grid of map panels sized to the domain aspect ratio so titles don't collide."""
    nrows, ncols = grid_layout(n)
    panel_w = 3.0
    panel_h = panel_w * aspect + 0.30 * title_lines
    fig, axes = plt.subplots(
        nrows, ncols, figsize=(panel_w * ncols, panel_h * nrows), dpi=dpi, squeeze=False
    )
    fig.suptitle(title, fontsize=12, y=0.985)
    flat = axes.ravel()
    for ax in flat:
        ax.set_xticks([])
        ax.set_yticks([])
        for spine in ax.spines.values():
            spine.set_visible(False)
    return fig, flat


def finish_map_grid(fig, axes, n_used, out_path, dpi):
    for ax in axes[n_used:]:
        ax.set_visible(False)
    fig.tight_layout(rect=(0, 0, 1, 0.96), h_pad=2.0)
    fig.savefig(out_path, dpi=dpi, bbox_inches="tight")
    plt.close(fig)
    print(f"  wrote {out_path}")


# --- Figures -----------------------------------------------------------------


def plot_indicator_maps(members, domain_layer, baseline_indicator, layer, out_dir, dpi):
    """Small multiples of the indicator field, one panel per member."""
    fields = []
    if baseline_indicator is not None:
        fields.append(("baseline", baseline_indicator[layer]))
    for member_id, member_dir in members:
        ind = load_field(member_dir, "pf_indicator.pfb")
        if ind is None:
            print(f"  [warn] no pf_indicator.pfb for member {member_id}")
            continue
        fields.append((f"member {member_id}", ind[layer]))

    if not fields:
        print("  [warn] no indicator fields found; skipping indicator maps")
        return

    # Geologic units are nominal categories, so give each its own flat color and a
    # tick-per-class colorbar rather than a continuous ramp.
    classes = np.unique(np.concatenate([f[domain_layer].ravel() for _, f in fields]))
    cmap = ListedColormap(plt.get_cmap("tab20")(np.linspace(0, 1, 20))[: len(classes)])
    cmap.set_bad("#f0efec")
    lookup = {c: i for i, c in enumerate(classes)}
    norm = BoundaryNorm(np.arange(len(classes) + 1) - 0.5, cmap.N)

    aspect = fields[0][1].shape[0] / fields[0][1].shape[1]
    fig, axes = new_map_grid(
        len(fields), f"Indicator field, z-layer {layer} (geologic unit)", dpi, aspect
    )
    for ax, (label, field) in zip(axes, fields):
        coded = np.array([lookup.get(v, np.nan) for v in field.ravel()], dtype=float)
        coded = np.where(domain_layer.ravel(), coded, np.nan).reshape(field.shape)
        im = ax.imshow(
            np.ma.masked_invalid(coded),
            origin="lower",
            cmap=cmap,
            norm=norm,
            interpolation="nearest",
        )
        ax.set_title(label)

    cbar = fig.colorbar(
        im, ax=axes[: len(fields)].tolist(), fraction=0.02, pad=0.02, ticks=range(len(classes))
    )
    cbar.ax.set_yticklabels([f"{int(c)}" for c in classes], fontsize=7)
    cbar.set_label("unit id", color=INK_MUTED)
    cbar.outline.set_visible(False)

    for ax in axes[len(fields) :]:
        ax.set_visible(False)
    fig.savefig(os.path.join(out_dir, "indicator_maps.png"), dpi=dpi, bbox_inches="tight")
    plt.close(fig)
    print(f"  wrote {os.path.join(out_dir, 'indicator_maps.png')}")


def plot_indicator_change(members, domain, baseline_indicator, layer, out_dir, dpi):
    """Where each member's indicator field departs from the baseline."""
    if baseline_indicator is None:
        print("  [warn] no baseline indicator; skipping indicator change maps")
        return

    panels = []
    for member_id, member_dir in members:
        ind = load_field(member_dir, "pf_indicator.pfb")
        if ind is None:
            continue
        # Fractions are over active cells only, so an inactive halo can't dilute them.
        changed = (ind != baseline_indicator) & domain
        panels.append((member_id, changed[layer], changed.sum() / domain.sum()))

    if not panels:
        return

    fig, axes = new_map_grid(
        len(panels),
        f"Indicator cells changed from baseline, z-layer {layer}",
        dpi,
        aspect=panels[0][1].shape[0] / panels[0][1].shape[1],
        title_lines=2,
    )
    changed_cmap = ListedColormap(["#f0efec", ACCENT])
    for ax, (member_id, changed_layer, frac_all) in zip(axes, panels):
        ax.imshow(changed_layer, origin="lower", cmap=changed_cmap, vmin=0, vmax=1)
        frac_layer = changed_layer.sum() / max(domain[layer].sum(), 1)
        ax.set_title(
            f"member {member_id}\n{frac_layer:.1%} of layer, {frac_all:.1%} of volume",
            fontsize=9,
        )
    finish_map_grid(
        fig, axes, len(panels), os.path.join(out_dir, "indicator_change.png"), dpi
    )


def plot_parameter_map(members, runname, filename, label, layer, out_dir, out_name, dpi, log=False):
    """Small multiples of a realized 3D parameter field on a shared color scale."""
    panels = []
    for member_id, member_dir in members:
        field = load_field(member_dir, filename)
        if field is None:
            continue
        data = field[layer].astype(float)
        # ParFlow still writes values into inactive cells; blank them so every
        # figure shows the same domain outline and the color scale isn't skewed.
        data = np.where(active_mask(member_dir, runname, field.shape)[layer], data, np.nan)
        if log:
            data = np.log10(np.where(data > 0, data, np.nan))
        panels.append((member_id, data))

    if not panels:
        print(f"  [warn] no {filename} found; skipping {out_name}")
        return

    stacked = np.concatenate([d.ravel() for _, d in panels])
    vmin, vmax = np.nanpercentile(stacked, [1, 99])
    seq = SEQ_BLUE.copy()
    seq.set_bad("#f0efec")

    aspect = panels[0][1].shape[0] / panels[0][1].shape[1]
    fig, axes = new_map_grid(len(panels), f"{label}, z-layer {layer}", dpi, aspect)
    for ax, (member_id, data) in zip(axes, panels):
        im = ax.imshow(data, origin="lower", cmap=seq, vmin=vmin, vmax=vmax)
        ax.set_title(f"member {member_id}")

    cbar = fig.colorbar(im, ax=axes[: len(panels)].tolist(), fraction=0.02, pad=0.02)
    cbar.set_label(label, color=INK_MUTED)
    cbar.outline.set_visible(False)

    for ax in axes[len(panels) :]:
        ax.set_visible(False)
    fig.savefig(os.path.join(out_dir, out_name), dpi=dpi, bbox_inches="tight")
    plt.close(fig)
    print(f"  wrote {os.path.join(out_dir, out_name)}")


def load_baseline_params(baseline_runscript):
    """
    Unperturbed {unit: {perm, porosity}} from the baseline runscript.

    Returns {} if the runscript is missing or unreadable — the spread plot is
    still meaningful without the reference line.
    """
    if not os.path.isfile(baseline_runscript):
        return {}
    try:
        from parflow import Run

        from src.perturbations import _discover_geom_units

        run = Run.from_definition(baseline_runscript)
        return {
            name: {
                "perm": float(getattr(run.Geom, name).Perm.Value),
                "porosity": float(getattr(run.Geom, name).Porosity.Value),
            }
            for name in _discover_geom_units(run)
        }
    except Exception as exc:  # noqa: BLE001 - a missing reference line is not fatal
        print(f"  [warn] could not read baseline parameters: {exc}")
        return {}


def plot_parameter_spread(perturbations, baseline_params, out_dir, dpi):
    """Per-geom-unit parameter draws recorded in perturbation.json."""
    units = sorted(
        {u for params in perturbations.values() for u in params},
        key=lambda u: (re.sub(r"\d+$", "", u), int(re.search(r"\d+$", u).group()) if re.search(r"\d+$", u) else 0),
    )
    if not units:
        print("  [warn] no geom_params recorded; skipping parameter spread")
        return

    fig, axes = plt.subplots(2, 1, figsize=(max(7, 0.42 * len(units)), 7), dpi=dpi, sharex=True)
    x = np.arange(len(units))

    for ax, key, ylabel in (
        (axes[0], "perm", "permeability [m/h]"),
        (axes[1], "porosity", "porosity [-]"),
    ):
        values = np.full((len(perturbations), len(units)), np.nan)
        for r, params in enumerate(perturbations.values()):
            for c, unit in enumerate(units):
                if unit in params and params[unit].get(key) is not None:
                    values[r, c] = params[unit][key]

        # Members are interchangeable draws, so they get one recessive color; the
        # ensemble mean is the only series that carries identity.
        for r in range(values.shape[0]):
            ax.scatter(x, values[r], s=18, color=ACCENT, alpha=0.45, edgecolors="none", zorder=2)
        ax.scatter(
            x,
            np.nanmean(values, axis=0),
            s=46,
            marker="_",
            linewidths=2,
            color=ACCENT_WARM,
            zorder=3,
            label="ensemble mean",
        )
        if baseline_params:
            baseline = [baseline_params.get(u, {}).get(key, np.nan) for u in units]
            ax.scatter(
                x,
                baseline,
                s=60,
                marker="x",
                linewidths=1.4,
                color=INK,
                zorder=4,
                label="baseline",
            )
        ax.set_ylabel(ylabel)
        ax.grid(axis="y", linewidth=0.6, alpha=0.7)
        ax.set_axisbelow(True)
        for side in ("top", "right"):
            ax.spines[side].set_visible(False)
        ax.legend(loc="upper right")

    axes[0].set_yscale("log")
    axes[0].set_title(
        f"Perturbed subsurface parameters by geologic unit ({len(perturbations)} members)",
        loc="left",
    )
    axes[1].set_xticks(x)
    axes[1].set_xticklabels(units, rotation=90, fontsize=8)
    axes[1].set_xlabel("geom unit")

    fig.tight_layout()
    out_path = os.path.join(out_dir, "param_spread.png")
    fig.savefig(out_path, dpi=dpi, bbox_inches="tight")
    plt.close(fig)
    print(f"  wrote {out_path}")


def pressure_timeseries(member_dir, runname, stride):
    """Domain-mean and surface-layer-mean pressure head over active cells."""
    files = sorted(glob.glob(os.path.join(member_dir, f"{runname}.out.press.*.pfb")))
    files = [f for f in files if not f.endswith(".dist")][::stride]
    if not files:
        return None, None, None

    steps = [int(re.search(r"press\.(\d+)\.pfb$", f).group(1)) for f in files]
    first = read_pfb(files[0])
    mask = active_mask(member_dir, runname, first.shape)
    surf_mask = mask[-1]

    domain_mean = np.empty(len(files))
    surface_mean = np.empty(len(files))
    for i, path in enumerate(files):
        press = read_pfb(path)
        domain_mean[i] = press[mask].mean()
        surface_mean[i] = press[-1][surf_mask].mean()
    return np.array(steps), domain_mean, surface_mean


def plot_pressure_timeseries(members, runname, stride, out_dir, dpi):
    series = []
    for member_id, member_dir in members:
        print(f"  reading pressure for member {member_id}...", flush=True)
        steps, domain_mean, surface_mean = pressure_timeseries(member_dir, runname, stride)
        if steps is None:
            print(f"  [warn] no pressure output for member {member_id}")
            continue
        series.append((member_id, steps, domain_mean, surface_mean))

    if not series:
        print("  [warn] no pressure output found; skipping timeseries")
        return

    fig, axes = plt.subplots(2, 1, figsize=(9, 6.5), dpi=dpi, sharex=True)

    for ax, idx, ylabel, title in (
        (axes[0], 2, "mean pressure head [m]", "Whole-domain mean"),
        (axes[1], 3, "mean pressure head [m]", "Surface layer mean"),
    ):
        for j, entry in enumerate(series):
            ax.plot(
                entry[1],
                entry[idx],
                linewidth=1.0,
                color=ACCENT,
                alpha=0.45,
                zorder=2,
                label="ensemble members" if j == 0 else None,
            )

        # Members share a time axis only if they ran the same number of steps.
        lengths = {len(entry[1]) for entry in series}
        if len(lengths) == 1:
            stack = np.vstack([entry[idx] for entry in series])
            ax.plot(
                series[0][1],
                stack.mean(axis=0),
                linewidth=2.0,
                color=ACCENT_WARM,
                zorder=3,
                label="ensemble mean",
            )

        ax.set_ylabel(ylabel)
        ax.set_title(title, loc="left")
        ax.grid(axis="y", linewidth=0.6, alpha=0.7)
        ax.set_axisbelow(True)
        for side in ("top", "right"):
            ax.spines[side].set_visible(False)
        ax.legend(loc="best")

    axes[1].set_xlabel("timestep [h]")
    fig.suptitle(f"Mean pressure head, {len(series)} members", fontsize=12, y=0.99)
    fig.tight_layout(rect=(0, 0, 1, 0.97))
    out_path = os.path.join(out_dir, "pressure_timeseries.png")
    fig.savefig(out_path, dpi=dpi, bbox_inches="tight")
    plt.close(fig)
    print(f"  wrote {out_path}")


def main():
    args = parse_args()

    paths = resolve_paths(args)
    ensemble_dir = paths["ensemble_dir"]
    out_dir = args.out_dir or os.path.join(ensemble_dir, "figures")
    os.makedirs(out_dir, exist_ok=True)

    members = find_members(ensemble_dir, args.max_members)
    print(f"Found {len(members)} ensemble members in {ensemble_dir}")
    print(f"Writing figures to {out_dir}")

    baseline_indicator_path = os.path.join(paths["static_dir"], "pf_indicator.pfb")
    baseline_indicator = (
        read_pfb(baseline_indicator_path)
        if os.path.isfile(baseline_indicator_path)
        else None
    )
    if baseline_indicator is None:
        print(f"  [warn] baseline indicator not found at {baseline_indicator_path}")

    shape = load_field(members[0][1], "pf_indicator.pfb").shape
    layer = args.layer % shape[0]
    domain = active_mask(members[0][1], args.runname, shape)

    print("\nIndicator maps...")
    plot_indicator_maps(members, domain[layer], baseline_indicator, layer, out_dir, args.dpi)
    plot_indicator_change(members, domain, baseline_indicator, layer, out_dir, args.dpi)

    print("\nParameter maps...")
    plot_parameter_map(
        members,
        args.runname,
        f"{args.runname}.out.perm_x.pfb",
        "log10 permeability [m/h]",
        layer,
        out_dir,
        "param_map_perm.png",
        args.dpi,
        log=True,
    )
    plot_parameter_map(
        members,
        args.runname,
        f"{args.runname}.out.porosity.pfb",
        "porosity [-]",
        layer,
        out_dir,
        "param_map_porosity.png",
        args.dpi,
    )
    plot_parameter_spread(
        load_perturbations(members),
        load_baseline_params(paths["baseline_runscript"]),
        out_dir,
        args.dpi,
    )

    if not args.skip_timeseries:
        print("\nPressure timeseries...")
        plot_pressure_timeseries(members, args.runname, max(1, args.time_stride), out_dir, args.dpi)

    print("\nDone.")


if __name__ == "__main__":
    main()
